# Generated by Django 5.0.2 on 2024-02-09 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_college'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='uid',
            new_name='user_id',
        ),
    ]
