# Generated by Django 5.0.2 on 2024-02-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='picture',
            field=models.FileField(blank=True, upload_to='img/'),
        ),
    ]
