# Generated by Django 5.0.2 on 2024-02-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_company_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='c_picture',
            field=models.FileField(blank=True, default='', upload_to='img/'),
        ),
    ]
