# Generated by Django 5.0.2 on 2024-02-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_college_c_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
