# Generated by Django 5.0.2 on 2024-03-05 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_company_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='c_id',
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
