# Generated by Django 5.0.2 on 2024-03-17 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='c_id',
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
