# Generated by Django 5.0.2 on 2024-03-18 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll', models.CharField(max_length=12)),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('resume', models.FileField(blank=True, default='', upload_to='resume')),
                ('s_picture', models.FileField(blank=True, default='', upload_to='img/')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.user')),
            ],
        ),
    ]
