# Generated by Django 5.0.2 on 2024-03-18 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0012_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='c_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='s_id',
            new_name='user_id',
        ),
    ]
