# Generated by Django 5.0.2 on 2024-03-18 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0013_rename_c_id_company_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=10)),
                ('vac_count', models.CharField(max_length=2)),
                ('date', models.DateTimeField(auto_now=True)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.company')),
            ],
        ),
    ]
