# Generated by Django 5.0.2 on 2024-03-18 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0016_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='com_id',
        ),
    ]
