# Generated by Django 5.0.2 on 2024-03-19 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0017_remove_vacancy_com_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='date',
        ),
    ]
