# Generated by Django 5.0.2 on 2024-03-19 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0018_remove_vacancy_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
