# Generated by Django 5.0.2 on 2024-03-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0020_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='Pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vac_count',
            field=models.CharField(max_length=5),
        ),
    ]
