# Generated by Django 5.0.2 on 2024-03-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0021_user_status_alter_vacancy_vac_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
