# Generated by Django 5.0.2 on 2024-03-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0023_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='name',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
