# Generated by Django 5.0.2 on 2024-03-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0024_college_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
