# Generated by Django 5.0.2 on 2024-03-26 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0025_college_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='user_id',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='com_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='college.company'),
            preserve_default=False,
        ),
    ]
