# Generated by Django 5.0.2 on 2024-03-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0026_remove_vacancy_user_id_vacancy_com_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='com_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Vacancy',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
