# Generated by Django 5.0.2 on 2024-03-26 13:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0027_remove_company_user_id_remove_vacancy_com_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hr_f_name', models.CharField(max_length=20)),
                ('hr_l_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=10)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('about', models.CharField(blank=True, max_length=1500)),
                ('owner', models.CharField(blank=True, max_length=20)),
                ('reg_date', models.CharField(default=datetime.datetime.now, max_length=12)),
                ('picture', models.FileField(blank=True, upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll', models.CharField(max_length=12)),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True)),
                ('remarks', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('reg_date', models.DateTimeField(default=datetime.datetime.now, max_length=12)),
                ('resume', models.FileField(blank=True, default='', upload_to='resume')),
                ('s_picture', models.FileField(blank=True, default='', upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('otp', models.IntegerField(default=459)),
                ('status', models.CharField(default='Pending', max_length=7)),
                ('is_activate', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messege', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('time', models.DateTimeField()),
                ('status', models.CharField(max_length=200)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.company')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.student')),
            ],
        ),
        migrations.CreateModel(
            name='Suggetion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, max_length=12)),
                ('subject', models.CharField(max_length=50)),
                ('messege', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.user')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.user'),
        ),
        migrations.AddField(
            model_name='company',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.user'),
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('c_picture', models.FileField(blank=True, default='', upload_to='img/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.user')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=10)),
                ('post_des', models.CharField(max_length=500)),
                ('min_salary', models.CharField(max_length=10)),
                ('max_salary', models.CharField(max_length=10)),
                ('date', models.DateTimeField(default=datetime.datetime.now, max_length=12)),
                ('vac_count', models.CharField(max_length=5)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.company')),
            ],
        ),
    ]
