# Generated by Django 5.0.2 on 2024-03-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0028_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='c_picture',
            field=models.FileField(blank=True, default='img/def.jpg', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='picture',
            field=models.FileField(blank=True, default='img/def.jpg', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_picture',
            field=models.FileField(blank=True, default='img/def.jpg', upload_to='img/'),
        ),
    ]
