# Generated by Django 5.0.2 on 2024-03-27 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0029_alter_college_c_picture_alter_company_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggetion',
            name='user_id',
        ),
        migrations.AddField(
            model_name='suggetion',
            name='s_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='college.student'),
            preserve_default=False,
        ),
    ]
