# Generated by Django 5.0.2 on 2024-03-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0030_remove_suggetion_user_id_suggetion_s_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggetion',
        ),
    ]
