# Generated by Django 5.0.2 on 2024-03-27 10:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0031_delete_suggetion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggetion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now, max_length=12)),
                ('subject', models.CharField(max_length=50)),
                ('messege', models.CharField(max_length=500)),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.student')),
            ],
        ),
    ]
