# Generated by Django 5.0.2 on 2024-03-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0032_suggetion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
