# Generated by Django 5.0.2 on 2024-04-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0036_alter_interview_messege_apply_delete_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='max_salary',
            new_name='language',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='min_salary',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='post',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='post_des',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='date',
            field=models.DateTimeField(max_length=12),
        ),
    ]
