# Generated by Django 5.0.2 on 2024-04-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0037_rename_max_salary_vacancy_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='date',
            field=models.DateField(max_length=12),
        ),
    ]
