# Generated by Django 5.0.2 on 2024-04-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0038_alter_vacancy_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='com_id',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='sid',
        ),
        migrations.DeleteModel(
            name='Apply',
        ),
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
