# Generated by Django 5.0.2 on 2024-04-22 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0039_remove_interview_com_id_remove_interview_sid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.company')),
                ('s_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.student')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messege', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(default='Pending', max_length=200)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.apply')),
            ],
        ),
    ]
