# Generated by Django 5.0.2 on 2024-04-22 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0040_apply_interview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='messege',
        ),
    ]
